Features
ricardo123321/bubble_sort pull request #1
Opened 2020-04-28 17:54 UTC by ricardo123321

in this code we made a bubble sort method and a bubble sort-by method who organize the elements given in an array or a block

2020-04-28 21:15 UTC, shshamim63 requested changes
## Status :traffic_light: Required Changes :tractor: 
___
Hi @ricardo123321 and @paulo-techie :wave: ,
Awesome job. Just a couple of things to do before declaring this project as approved. Check the comments below...
___
### :spades: Mandatory Changes :spades: 
___
1. Both of your methods are not returning the modified array. Please check the comments below to fix them.
2. I can not see any descriptive readme in this repository. Please add one.
___
##### Please fix the above-mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-04-28 21:15 UTC, shshamim63 commented on feature.rb
> +  end
bubble sort returns a sorted array. But, based on your current formation it returns nil. after line 11, place `array`.

2020-04-28 21:15 UTC, shshamim63 commented on feature.rb
> +  end
Same in here too. it is returning nil. So after line 25 place `array`

2020-04-29 02:04 UTC, euqueme approved these changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @ricardo123321 and @paulo-techie :balloon: :lollipop: 

### Thank you for doing the changes requested by the previous reviewer, your methods are working fine, please merge this branch and continue congratulations :tada: :tada: :tada: 

[OPTIONAL]

- [x] I strongly recommend the use of `array.size` instead of `array.length` to keep the Ruby convention

PROJECT STATUS: APPROVED :green_apple:

2020-04-29 14:50 UTC, merged